import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./style.css';
const sb=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const fiSex={male:'Uros',female:'Naaras',unknown:'Tuntematon'};
function App(){const[user,setUser]=useState(null),[email,setEmail]=useState(''),[tab,setTab]=useState('upload'),[msg,setMsg]=useState(''),[obs,setObs]=useState([]),[inds,setInds]=useState([]),[cams,setCams]=useState([]),[stats,setStats]=useState([0,0,0]),[form,setForm]=useState({dt:'',camera:'',sex:'unknown',age:'',left:'',right:'',notes:''}),[file,setFile]=useState(null);
useEffect(()=>{sb.auth.getSession().then(({data})=>setUser(data.session?.user||null));const{x}= {x:sb.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null))};return()=>x.data.subscription.unsubscribe()},[]);
useEffect(()=>{if(user)load()},[user]);
async function load(){let{data:c}=await sb.from('cameras').select('*').order('name');if(!c?.length){await sb.from('cameras').insert({name:'Riistakamera 1'});({data:c}=await sb.from('cameras').select('*'))}setCams(c||[]);setForm(f=>({...f,camera:c?.[0]?.id||'',dt:new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}));await Promise.all([loadObs(),loadInd(),counts()])}
async function counts(){let[a,b,c]=await Promise.all([sb.from('observations').select('*',{count:'exact',head:true}),sb.from('detections').select('*',{count:'exact',head:true}),sb.from('individuals').select('*',{count:'exact',head:true})]);setStats([a.count||0,b.count||0,c.count||0])}
async function loadObs(){let{data}=await sb.from('detections').select('id,sex,age_class,antler_points_left,antler_points_right,image_path,observations(observed_at,notes)').order('created_at',{ascending:false});for(let d of data||[]){let{data:s}=await sb.storage.from('moose-images').createSignedUrl(d.image_path,3600);d.url=s?.signedUrl}setObs(data||[])}
async function loadInd(){let{data}=await sb.from('individuals').select('*').order('code');setInds(data||[])}
async function login(){let{error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});setMsg(error?error.message:'Kirjautumislinkki lähetetty sähköpostiin.')}
async function save(e){e.preventDefault();if(!file)return setMsg('Valitse kuva.');setMsg('Tallennetaan…');let ext=file.name.split('.').pop()||'jpg',path=user.id+'/'+Date.now()+'-'+crypto.randomUUID()+'.'+ext;let{error}=await sb.storage.from('moose-images').upload(path,file,{contentType:file.type});if(error)return setMsg(error.message);let{data:o,error:oe}=await sb.from('observations').insert({observed_at:form.dt?new Date(form.dt).toISOString():null,camera_id:form.camera,notes:form.notes}).select().single();if(oe)return setMsg(oe.message);let{error:de}=await sb.from('detections').insert({observation_id:o.id,image_path:path,sex:form.sex,age_class:form.age||null,antler_points_left:form.left?+form.left:null,antler_points_right:form.right?+form.right:null,antler_notes:form.notes});setMsg(de?de.message:'Havainto tallennettu.');if(!de){setFile(null);await Promise.all([loadObs(),counts()])}}
async function addInd(e){e.preventDefault();let fd=new FormData(e.currentTarget),code=fd.get('code');if(!code)return;await sb.from('individuals').insert({code,nickname:fd.get('name')||null});e.currentTarget.reset();loadInd();counts()}
if(!user)return <div className="shell"><header><b>🫎 Vehkamäki Moose ID</b><small>Hirviyksilöiden seuranta</small></header><section className="card login"><h1>Kirjaudu</h1><p>Riistakamerakuvat ja havaintotiedot säilyvät yksityisinä.</p><input type="email" placeholder="Sähköposti" value={email} onChange={e=>setEmail(e.target.value)}/><button onClick={login}>Lähetä kirjautumislinkki</button>{msg&&<div className="notice">{msg}</div>}</section></div>;
return <div className="shell"><header><div><b>🫎 Vehkamäki Moose ID</b><small>Vehkamäen hirviyksilöiden seuranta</small></div><button className="secondary" onClick={()=>sb.auth.signOut()}>Ulos</button></header><div className="stats">{['Havainnot','Kuvat / eläimet','Tunnistetut yksilöt'].map((x,i)=><div className="card stat" key={x}><small>{x}</small><strong>{stats[i]}</strong></div>)}</div><nav>{[['upload','Lisää havainto'],['obs','Havainnot'],['inds','Yksilöt'],['ai','AI-tunnistus']].map(([k,v])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{v}</button>)}</nav>
{tab==='upload'&&<form className="card" onSubmit={save}><h2>Uusi riistakamerahavainto</h2><div className="two"><label>Aika<input type="datetime-local" value={form.dt} onChange={e=>setForm({...form,dt:e.target.value})}/></label><label>Kamera<select value={form.camera} onChange={e=>setForm({...form,camera:e.target.value})}>{cams.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><label>Kuva<input type="file" accept="image/*" onChange={e=>setFile(e.target.files[0])}/></label>{file&&<img className="preview" src={URL.createObjectURL(file)}/>}<div className="two"><label>Sukupuoli<select value={form.sex} onChange={e=>setForm({...form,sex:e.target.value})}><option value="unknown">Tuntematon</option><option value="male">Uros</option><option value="female">Naaras</option></select></label><label>Ikäluokka<select value={form.age} onChange={e=>setForm({...form,age:e.target.value})}><option value="">Ei arviota</option><option>vasa</option><option>nuori</option><option>aikuinen</option><option>vanha</option></select></label></div><div className="two"><label>Vasen sarvipuoli<input type="number" min="0" value={form.left} onChange={e=>setForm({...form,left:e.target.value})}/></label><label>Oikea sarvipuoli<input type="number" min="0" value={form.right} onChange={e=>setForm({...form,right:e.target.value})}/></label></div><label>Huomiot<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Sarvien muoto, tuntomerkit, käyttäytyminen…"/></label><button>Tallenna havainto</button>{msg&&<div className="notice">{msg}</div>}</form>}
{tab==='obs'&&<section className="card"><h2>Havainnot</h2>{obs.length?obs.map(d=><article className="ob" key={d.id}>{d.url&&<img src={d.url}/>}<div><b>{d.observations?.observed_at?new Date(d.observations.observed_at).toLocaleString('fi-FI'):'Ei aikaa'}</b><p><span>{fiSex[d.sex]||d.sex}</span> <span>{d.age_class||'ikä ?'}</span></p><p>Sarvet: {d.antler_points_left??'?'} + {d.antler_points_right??'?'}</p><small>{d.observations?.notes}</small></div></article>):<p>Ei havaintoja vielä.</p>}</section>}
{tab==='inds'&&<section className="card"><h2>Yksilörekisteri</h2><form className="inline" onSubmit={addInd}><input name="code" placeholder="U007" required/><input name="name" placeholder="Nimi / lempinimi"/><button>Lisää</button></form>{inds.map(i=><article className="ind" key={i.id}><b>{i.code}</b> {i.nickname&&'— '+i.nickname}<span>{i.status}</span></article>)}</section>}
{tab==='ai'&&<section className="card"><h2>AI-tunnistus</h2><p>Järjestelmän seuraava vaihe vertailee uutta hirveä aiempiin kuviin ja näyttää Top-5 ehdokkaat.</p><div className="score"><b>Season-ID</b><small>Sarvet + pää + vartalo, saman vuoden tunnistus</small></div><div className="score"><b>Lifetime-ID</b><small>Pää + korvat + vartalo, sarvien vaikutusta vähennetään vuosien välillä</small></div><div className="notice">Tietokanta tukee jo 768-ulotteisia embedding-vektoreita ja nopeaa HNSW-hakua. Lopullinen tunnistus jätetään käyttäjän vahvistettavaksi: SAMA / ERI / EPÄVARMA.</div></section>}</div>}
createRoot(document.getElementById('root')).render(<App/>);